//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainManagementWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRuleDistance
    {
        public int Id { get; set; }
        public string RulName { get; set; }
        public string RuleType { get; set; }
        public Nullable<decimal> StartStation { get; set; }
        public Nullable<decimal> EndStation { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<double> Value { get; set; }
    }
}
