//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainManagementWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStation()
        {
            this.tblBookingDetails = new HashSet<tblBookingDetail>();
            this.tblBookingDetails1 = new HashSet<tblBookingDetail>();
            this.tblTrainSchedules = new HashSet<tblTrainSchedule>();
        }
    
        public decimal Id { get; set; }
        public string StationName { get; set; }
        public string StationCode { get; set; }
        public string RailwayDivisionName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> PositonDistance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingDetail> tblBookingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBookingDetail> tblBookingDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainSchedule> tblTrainSchedules { get; set; }
    }
}
