//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainManagementWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTrain()
        {
            this.tblTrainDetails = new HashSet<tblTrainDetail>();
            this.tblTrainSchedules = new HashSet<tblTrainSchedule>();
        }
    
        public decimal Id { get; set; }
        public string TrainName { get; set; }
        public string TrainCode { get; set; }
        public string TrainNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ACCoaches { get; set; }
        public Nullable<int> FirstClassCoaches { get; set; }
        public Nullable<int> SleeperClassCoaches { get; set; }
        public Nullable<decimal> ProposedPrice { get; set; }
        public Nullable<int> ACSeats { get; set; }
        public Nullable<int> FirstClassSeats { get; set; }
        public Nullable<int> SleeperClassSeats { get; set; }
        public string Route { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainDetail> tblTrainDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTrainSchedule> tblTrainSchedules { get; set; }
    }
}
