//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainManagementWeb.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainSchedule
    {
        public decimal id { get; set; }
        public Nullable<decimal> TrainId { get; set; }
        public Nullable<decimal> StationId { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string DepartureTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblStation tblStation { get; set; }
        public virtual tblTrain tblTrain { get; set; }
    }
}
