//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainManagementWeb.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TrainManagementEntities : DbContext
    {
        public TrainManagementEntities()
            : base("name=TrainManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblBookingDetail> tblBookingDetails { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblRuleCancelBooking> tblRuleCancelBookings { get; set; }
        public virtual DbSet<tblRuleClass> tblRuleClasses { get; set; }
        public virtual DbSet<tblRuleDistance> tblRuleDistances { get; set; }
        public virtual DbSet<tblStation> tblStations { get; set; }
        public virtual DbSet<tblTrain> tblTrains { get; set; }
        public virtual DbSet<tblTrainDetail> tblTrainDetails { get; set; }
        public virtual DbSet<tblTrainSchedule> tblTrainSchedules { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<View_GetTrainSchedule> View_GetTrainSchedule { get; set; }
    
        public virtual ObjectResult<sp_User_Login_Result> sp_User_Login(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_User_Login_Result>("sp_User_Login", emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_GetTrainSchedule_Result> sp_GetTrainSchedule(string departureStationName, string arrivalStationName)
        {
            var departureStationNameParameter = departureStationName != null ?
                new ObjectParameter("DepartureStationName", departureStationName) :
                new ObjectParameter("DepartureStationName", typeof(string));
    
            var arrivalStationNameParameter = arrivalStationName != null ?
                new ObjectParameter("ArrivalStationName", arrivalStationName) :
                new ObjectParameter("ArrivalStationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTrainSchedule_Result>("sp_GetTrainSchedule", departureStationNameParameter, arrivalStationNameParameter);
        }
    
        public virtual ObjectResult<sp_GetTrainScheduleList_Result> sp_GetTrainScheduleList(string departureStationName, string arrivalStationName)
        {
            var departureStationNameParameter = departureStationName != null ?
                new ObjectParameter("DepartureStationName", departureStationName) :
                new ObjectParameter("DepartureStationName", typeof(string));
    
            var arrivalStationNameParameter = arrivalStationName != null ?
                new ObjectParameter("ArrivalStationName", arrivalStationName) :
                new ObjectParameter("ArrivalStationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTrainScheduleList_Result>("sp_GetTrainScheduleList", departureStationNameParameter, arrivalStationNameParameter);
        }
    }
}
